-- DDL generated by Postico 2.0.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "user" (
    user_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    phone_number text NOT NULL,
    roles text NOT NULL,
    picture_url text,
    country_code text NOT NULL,
    gender text NOT NULL,
    date_of_birth date NOT NULL,
    password text NOT NULL,
    sex character varying(1) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON "user"(user_id int8_ops);



-- DDL generated by Postico 2.0.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_metadata (
    metadata_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint GENERATED ALWAYS AS IDENTITY REFERENCES "user"(user_id),
    is_blocked bit(1) NOT NULL,
    is_deleted bit(1) NOT NULL,
    is_trial bit(1) NOT NULL,
    is_premium bit(1) NOT NULL,
    is_active bit(1) NOT NULL,
    is_cred_expired bit(1) NOT NULL,
    deleted_by text,
    last_login date,
    modified_time date,
    trial_start date,
    trial_end date,
    password_last_modified date
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_metadata_pkey ON user_metadata(metadata_id int8_ops);
